### ISSUE TITLE
"Too many open files" error

### ISSUE THREAD

**Issue by Monkstar** [UHH-ISS/honeygrove#16] opened 2018-01-15 23:19 UTC
After a while (usually a few days), the honeypot sometimes stops working with errors like this:

```
Exception in thread HeartbeatThread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
  File "/usr/lib/python3.5/threading.py", line 862, in run
  File "/home/jens/bp-itsec/honeygrove/core/HoneyAdapter.py", line 43, in hearbe                                                                                                                                                             at
  File "/home/jens/bp-itsec/honeygrove/logging/log.py", line 228, in heartbeat
  File "/home/jens/bp-itsec/honeygrove/logging/log.py", line 18, in write
OSError: [Errno 24] Too many open files: '/home/jens/bp-itsec/honeygrove/resourc                                                                                                                                                             es/logfile/log.txt'
```

It turns out, there are apparently too many open SSH connections as you can see in the attached file including an lsof output when the error occured.

[Error.txt](https://github.com/UHH-ISS/honeygrove/files/1633207/Error.txt)

**Comment by jfrangop** [comment] 2018-01-16 09:29
Duplicate of #13

**Closed** 2018-02-06 11:28 UTC
